<a href="https://colab.research.google.com/github/fatimakhazaeni/_my_ai_repo/blob/main/EX4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded=files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
dataset=pd.read_csv('Churn_Modelling.csv')
X=dataset.iloc[:,3:-1].values
Y=dataset.iloc[:,-1].values

In [3]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

ANN IMPLMNT

In [5]:
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [6]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
ann.fit(X_train,Y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5976 - accuracy: 0.6873
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4688 - accuracy: 0.8016
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4437 - accuracy: 0.8083
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4277 - accuracy: 0.8169
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4137 - accuracy: 0.8214
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3995 - accuracy: 0.8265
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3859 - accuracy: 0.8356
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3756 - accuracy: 0.8419
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3685 - accuracy: 0.8455
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3634 - accura

In [7]:
Y_pred=ann.predict(X_test)
Y_pred=(Y_pred>0.5)
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(Y_test,Y_pred)
print(cm)
accuracy_score(Y_test,Y_pred)

63/63 [==============================] - 0s 2ms/step
[[1518   77]
 [ 195  210]]


0.864

# New Section